apiVersion: v1
data:
  mapRoles: |
    - groups:
      -system:masters
      rolearn: arn:aws:iam::448465605637:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::448465605637:role/eksctl-eksctl-demo2-nodegroup-ng-NodeInstanceRole-1EOHNSVF8P2TI
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-03T16:01:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1566"
  uid: 3142d6f2-2b17-4c9d-ba10-6ae331986328
